services:
  - type: web
    name: php-backend
    env: docker
    plan: free
    repo: https://github.com/Dhruil/finmypg_backend.git
    branch: main
    rootDir: /
    dockerContext: .
    dockerfilePath: ./Dockerfile
